### PR TITLE
Update/profile seeds

### PR DESCRIPTION
**Pull request by Samuel-Torres**

### CODE REVIEW

**Review by april5622 — APPROVED** [review]
A much better solution then using null.

**Review by april5622 — COMMENTED** [review]
Also a test have failed

**Review by elijahmandeville — CHANGES_REQUESTED** [review]
You're getting some linting errors. You'll need to run `npm run lint:fix`

**Review by elijahmandeville — APPROVED** [review]
Tests pass and it looks good!

**Pull request merged**
